### ISSUE TITLE
mac os 

### ISSUE THREAD

**Issue by vondragh** [mohsenph69/Godot-MTerrain-plugin#23]
Is it possible to use the addon on Mac OS?
If this is not possible, please provide support for Mac OS :)

**Comment by vondragh** [comment]
Unable to load addon script at path: 'res://addons/m_terrain/m_terrain.gd'. This may be due to an error in the script code.
Disabling addon 'res://addons/m_terrain/plugin.cfg' to prevent further errors.

**Comment by mohsenph69** [comment]
Off-course it is possible, unfortunately I don't have a mac os but obviously this should work also on mac os.

I will try to install Mac Os on a virtual box and see if I can make this running! anyway I will write some instruction about how you can build this library down bellow, _see if you can make this running_, if you can not wait until I will figure out how can I make this run on Mac Os!

Regarding of error your talking about, does this give any error message, if yes please past that here! (But obviously this error can be because the library for mterrain is not build for mac os and because of that it can not recognize MTerrain and other classes in MTerrain library, So it can not be activated, and if you build the library it will work)

You need to install, **git**, **python**, **scons** and a **c++ compiler**! After that clone M Terrain repo inside addon folder in Godot project!

run this command inside addon folder
`git clone https://github.com/mohsenph69/Godot-MTerrain-plugin.git`

Then change the name of the repo folder to `m_terrain`

go inside that folder and run this command

`git submodule update --init --recursive` This will download godot-cpp and it put it inside gdextension folder

After that go inside Gdextension folder and run `scons` command, This should build for debug version of M Terrain plugin

for release version you should run `scons target=template_release`

This will add terrain library inside lib folder in addon directory, you also need to set the path of lib inside `MTerrain.gdextension` like this 

```
macos.debug = "res://addons/m_terrain/libs/libMTerrain.macos.template_debug.framework"
macos.release = "res://addons/m_terrain/libs/libMTerrain.macos.template_release.framework"
```

Also please note this will not work on Godot 4.0, But it will work on Godot 4.1 , 4.2

If you can make that running let me know, also if you got any error let me know

**Comment by x3haloed** [comment]
@vondragh Did you get it working?

I too would love to having this working for macOS. I'm encountering the following error:   `core/extension/gdextension.cpp:911 - No GDExtension library found for current OS and architecture (macos.arm64) in configuration file: res://addons/m_terrain/libs/MTerrain.gdextension`

**Comment by x3haloed** [comment]
Oh no. Build failed!

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/stdlib.h:131:1: note: candidate function
abs(long double __lcpp_x) _NOEXCEPT {
^
src/grass/mgrass.cpp:501:30: error: call to 'abs' is ambiguous
            uint32_t dif_y = UABS_DIFF(y,brush_px_pos_y);
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/grass/../mconfig.h:42:25: note: expanded from macro 'UABS_DIFF'
#define UABS_DIFF(a, b) abs(a-b)
                        ^~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:132:6: note: candidate function
int      abs(int) __pure2;
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/stdlib.h:113:61: note: candidate function
_LIBCPP_NODISCARD_EXT inline _LIBCPP_INLINE_VISIBILITY long abs(long __x) _NOEXCEPT {
                                                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/stdlib.h:116:66: note: candidate function
_LIBCPP_NODISCARD_EXT inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {
                                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/stdlib.h:122:62: note: candidate function
_LIBCPP_NODISCARD_EXT inline _LIBCPP_INLINE_VISIBILITY float abs(float __lcpp_x) _NOEXCEPT {
                                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/stdlib.h:126:63: note: candidate function
_LIBCPP_NODISCARD_EXT inline _LIBCPP_INLINE_VISIBILITY double abs(double __lcpp_x) _NOEXCEPT {
                                                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/stdlib.h:131:1: note: candidate function
abs(long double __lcpp_x) _NOEXCEPT {
^
2 errors generated.
scons: *** [src/grass/mgrass.os] Error 1
scons: building terminated because of errors.
```

**Comment by vondragh** [comment]
I have the same thing during the collection, when it is assembled and when it ends, some .os files are not created, but only some say that there is an error

**Comment by mohsenph69** [comment]
I will install mac os on virtually machine, and I see if I can fix that!

**Comment by mohsenph69** [comment]
And I could not install MacOs on virtual machine, But I will try that later!

But I solve the problem which cause the error you sended me!

**Comment by x3haloed** [comment]
More issues, unfortunately 😢

```
clang++ -o src/mgrid.os -c -std=c++17 -arch x86_64 -arch arm64 -O2 -fPIC -DMACOS_ENABLED -DUNIX_ENABLED -DDEBUG_ENABLED -DDEBUG_METHODS_ENABLED -DNDEBUG -Igodot-cpp/gdextension -Igodot-cpp/include -Igodot-cpp/gen/include -Isrc src/mgrid.cpp
1 warning generated.
clang++ -o src/mbrush_layers.os -c -std=c++17 -arch x86_64 -arch arm64 -O2 -fPIC -DMACOS_ENABLED -DUNIX_ENABLED -DDEBUG_ENABLED -DDEBUG_METHODS_ENABLED -DNDEBUG -Igodot-cpp/gdextension -Igodot-cpp/include -Igodot-cpp/gen/include -Isrc src/mbrush_layers.cpp
clang++ -o src/color_brushes/mpaint_256.os -c -std=c++17 -arch x86_64 -arch arm64 -O2 -fPIC -DMACOS_ENABLED -DUNIX_ENABLED -DDEBUG_ENABLED -DDEBUG_METHODS_ENABLED -DNDEBUG -Igodot-cpp/gdextension -Igodot-cpp/include -Igodot-cpp/gen/include -Isrc src/color_brushes/mpaint_256.cpp
clang++ -o src/height_brushes/mremove_layer.os -c -std=c++17 -arch x86_64 -arch arm64 -O2 -fPIC -DMACOS_ENABLED -DUNIX_ENABLED -DDEBUG_ENABLED -DDEBUG_METHODS_ENABLED -DNDEBUG -Igodot-cpp/gdextension -Igodot-cpp/include -Igodot-cpp/gen/include -Isrc src/height_brushes/mremove_layer.cpp
src/mimage.cpp:859:10: warning: 27 enumeration values not handled in switch: 'FORMAT_RH', 'FORMAT_RGH', 'FORMAT_RGBH'... [-Wswitch]
        switch (p_format) {
                ^~~~~~~~
src/mimage.cpp:859:10: note: add missing switch cases
        switch (p_format) {
                ^
clang++ -o src/grass/mgrass.os -c -std=c++17 -arch x86_64 -arch arm64 -O2 -fPIC -DMACOS_ENABLED -DUNIX_ENABLED -DDEBUG_ENABLED -DDEBUG_METHODS_ENABLED -DNDEBUG -Igodot-cpp/gdextension -Igodot-cpp/include -Igodot-cpp/gen/include -Isrc src/grass/mgrass.cpp
clang++ -o src/height_brushes/mtoheight.os -c -std=c++17 -arch x86_64 -arch arm64 -O2 -fPIC -DMACOS_ENABLED -DUNIX_ENABLED -DDEBUG_ENABLED -DDEBUG_METHODS_ENABLED -DNDEBUG -Igodot-cpp/gdextension -Igodot-cpp/include -Igodot-cpp/gen/include -Isrc src/height_brushes/mtoheight.cpp
1 warning generated.
clang++ -o src/mterrain_material.os -c -std=c++17 -arch x86_64 -arch arm64 -O2 -fPIC -DMACOS_ENABLED -DUNIX_ENABLED -DDEBUG_ENABLED -DDEBUG_METHODS_ENABLED -DNDEBUG -Igodot-cpp/gdextension -Igodot-cpp/include -Igodot-cpp/gen/include -Isrc src/mterrain_material.cpp
src/height_brushes/mtoheight.cpp:42:15: error: use of overloaded operator '=' is ambiguous (with operand types 'Variant' and 'long')
    p3["min"] = -10000000000;
    ~~~~~~~~~ ^ ~~~~~~~~~~~~
godot-cpp/include/godot_cpp/variant/variant.hpp:252:11: note: candidate function
        Variant &operator=(const Variant &other);
                 ^
godot-cpp/include/godot_cpp/variant/variant.hpp:253:11: note: candidate function
        Variant &operator=(Variant &&other);
                 ^
src/height_brushes/mtoheight.cpp:43:15: error: use of overloaded operator '=' is ambiguous (with operand types 'Variant' and 'long')
    p3["max"] = 100000000000;
    ~~~~~~~~~ ^ ~~~~~~~~~~~~
godot-cpp/include/godot_cpp/variant/variant.hpp:252:11: note: candidate function
        Variant &operator=(const Variant &other);
                 ^
godot-cpp/include/godot_cpp/variant/variant.hpp:253:11: note: candidate function
        Variant &operator=(Variant &&other);
                 ^
2 errors generated.
scons: *** [src/height_brushes/mtoheight.os] Error 1
scons: building terminated because of errors.
```

**Comment by mohsenph69** [comment]
So with the new release I also build for MacOs!

See if that work!

**Comment by cabarius** [comment]
I am trying to bring up m_terrain on a new project on mac in godot 4.2 and I am getting 

```
  Couldn't open MTL file 'res://addons/m_terrain/gui/human_male.mtl', it may not exist or not be readable.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  res://addons/m_terrain/gui/image_creator_window.gd:77 - Compile Error: Identifier not found: MResource
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/m_terrain/gui/image_creator_window.gd" with error "Compilation failed". (User)
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  res://addons/m_terrain/gui/import Godot res.gd:170 - Compile Error: Identifier not found: MResource
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/m_terrain/gui/import Godot res.gd" with error "Compilation failed". (User)
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  res://addons/m_terrain/gui/import_window.gd:221 - Compile Error: Identifier not found: MResource
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/m_terrain/gui/import_window.gd" with error "Compilation failed". (User)
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MBrushManager" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MBrushManager" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MBrushManager" not found.
  res://addons/m_terrain/gui/paint_panel.gd:33 - Compile Error: Identifier not found: MBrushManager
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/m_terrain/gui/paint_panel.gd" with error "Compilation failed". (User)
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MResource" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "MTerrain" not found.```

Did human_male.mtl get removed or renamed?

**Comment by arimus** [comment]
I tried to fetch the latest build and I see no Mac libs

**Comment by arimus** [comment]
FWIW, I also upgraded to the 4.2 branch of godot-cpp and rebuilt. Everything compiled fine without modifications to the scripts, but same deal with a crash on opening.
